# Generated by Django 5.1.6 on 2026-10-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=4)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='trip_amount_gt_0'), models.CheckConstraint(condition=models.Q(('commission__gte', 0)), name='trip_commission_gte_0'), models.CheckConstraint(condition=models.Q(('payment__in', ['cash', 'card'])), name='trip_payment_cash_or_card'), models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='trip_end_after_start')],
            },
        ),
    ]
